package com.wutong.mygreendao.green.dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wutong.mygreendao.green.dao.db.Student;
import com.wutong.mygreendao.green.dao.db.People;

import com.wutong.mygreendao.green.dao.db.StudentDao;
import com.wutong.mygreendao.green.dao.db.PeopleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig peopleDaoConfig;

    private final StudentDao studentDao;
    private final PeopleDao peopleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        peopleDaoConfig = daoConfigMap.get(PeopleDao.class).clone();
        peopleDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        peopleDao = new PeopleDao(peopleDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(People.class, peopleDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        peopleDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public PeopleDao getPeopleDao() {
        return peopleDao;
    }

}
